export const SET_CONTACTS = "SET_CONTACTS";
export const ADD_CONTACTS = "ADD_CONTACTS";
export const DELETE_CONTACTS = "DELETE_CONTACTS";
export const UPDATE_CONTACTS = "UPDATE_CONTACTS";
export const CONTACTS_FETCH_START = "CONTACTS_FETCH_START";
export const CONTACTS_FETCH_FINISHED = "CONTACTS_FETCH_FINISHED";
export const CONTACTS_FETCH_ERROR = "CONTACTS_FETCH_ERROR";
export const CONTACTS_FETCH_ERROR_CLEAN = "CONTACTS_FETCH_ERROR_CLEAN";
